"""init_db

Revision ID: b84833011207
Revises: 
Create Date: 2024-10-05 19:06:12.566543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84833011207'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Наименование блюда'),
    sa.Column('description_of_cooking', sa.String(), nullable=True, comment='Описание приготовления блюда'),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Блюда'
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='Наименование продукта'),
    sa.Column('measure', sa.String(length=32), nullable=False, comment='Мера измерения'),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Продукты'
    )
    op.create_table('products_in_dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish', sa.Integer(), nullable=True, comment='Ссылка на блюдо'),
    sa.Column('product', sa.Integer(), nullable=True, comment='Ссылка на продукт'),
    sa.Column('quantity', sa.NUMERIC(precision=15, scale=3), nullable=False, comment='Кол-во продукта в блюде'),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dish'], ['dishes.id'], ),
    sa.ForeignKeyConstraint(['product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Продукты в блюдах'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_in_dishes')
    op.drop_table('products')
    op.drop_table('dishes')
    # ### end Alembic commands ###
